#! /usr/bin/env python
#
# This script converts a cluster in the Chimes params file to Wolfram Mathematica format
#
# Usage: params_to_jit.py <chimes params file> <MODEL_NAME>
#        After performing this, there should be 3 files created
#        chimesJITcluster.MODEL_NAME.cpp (generated by mathematica) - contains Horner polynomial evaluations for cluster polys and their derivatives.
#        chimesJITev.MODEL_NAME.cpp (generated by this script) - contains a general evaluator for 3 and 4 body cluster polynomials.
#        chimesJITev.MODEL_NAME.h (generated by this script) - contains class definitions for the general evaluators and clusters.
#
import sys
import os
import shutil
from datetime import date

## Name of the installed mathematica command.  
mathematica = "math"

path = shutil.which(mathematica)
if path is None:
    print("Mathematica is not available")
    print("Run module load mathematica at LLNL")
    exit(1)
    
def print_4b_header(feval, fheader):
# Print header for 4-body interactions and finish up triplet evaluator
    print("  default: printf(\"Bad triplet index in ChimesJIT\") ; exit(1) ; ", file = feval)            
    print("  }", file = feval)
    print("}", file = feval)

    print(" ", file = feval)
    print("void ChimesJITev::poly_4B(double x0, double x1, double x2, double x3, double x4, double x5,", file = feval)
    print("                        int quadidx, double *e,", file = feval)
    print("                        double *f0, double *f1, double *f2, double *f3, double *f4, double *f5)", file = feval)
    print("{", file = feval)
    print("  switch(quadidx) {", file = feval)

    ## Definition in header
    print("   void poly_4B(double x0, double x1, double x2, double x3, double x4, double x5,", file = fheader)
    print("                int quadidx, double *e,", file = fheader)
    print("                double *f0, double *f1, double *f2, double *f3, double *f4, double *f5) ;", file = fheader)
    return


def print_3b_header(feval, fheader):
# Print header for 3-body interactions and finish up pair evaluator
    print("  default: printf(\"Bad pair index in ChimesJIT\") ; exit(1) ; ", file = feval)            
    print("  }", file = feval)
    print("}", file = feval)

    ## Start the general polynomial evaluator definition.
    print("\nvoid ChimesJITev::poly_3B(double x0, double x1, double x2, int tripidx, double *e,", file = feval)
    print("                        double *f0, double *f1, double *f2)", file = feval)
    print("{", file = feval)
    print("  switch(tripidx) {", file = feval)

    print("   void poly_3B(double x0, double x1, double x2, int tripidx, double *e,", file = fheader)
    print("                double *f0, double *f1, double *f2) ;", file = fheader)

def print_2b_header(feval, fheader):
# Print header for 2-body interactions. 
    ## Start the general polynomial evaluator definition.
    print("void ChimesJITev::poly_2B(double x0, int pairidx, double *e, double *f0)", file = feval)
    print("{", file = feval)
    print("  switch(pairidx) {", file = feval)

    print("   void poly_2B(double x0, int pairidx, double *e, double *f0) ;", file = fheader)
    

if ( len(sys.argv) != 3 ):
    print("Usage: params_to_jit.py <chimes parameter file> <model name>")
    
file = sys.argv[1]
model_name = sys.argv[2]

fp = open(file, "r")


## Strings to search for indicating pair, triplet, or quadruplet interaction.
pairsearch = "PAIRTYPE PARAMS"
tripsearch = "TRIPLETTYPE"
quadsearch = "QUADRUPLETYPE"

## String to search for chebyshev orders.
chebysearch = "PAIRTYP: CHEBYSHEV"

lines = fp.readlines()

feval = open("chimesJITev.cpp","w")
fheader = open("chimesJITev.h", "w")
fmath = open("chimesjit.m", "w")

print("file = OpenWrite[\"chimesJITcluster.cpp\"]", file=fmath)
print("WriteLine[file,\"#include \\\"chimesJITev.h\\\" \"]", file=fmath)

print("""
#include <stdio.h>
#include <stdlib.h>
#include <string>

inline double Power(double X, int pow)
{
  switch (pow) {
  case 0: return 1.0 ;
  case 1: return X ;
  case 2: return X*X ;
  case 3: return X*X*X ;
  case 4: return X*X*X*X ;
  case 5: return X*X*X*X*X ;
  case 6: return X*X*X*X*X*X ;
  case 7: return X*X*X*X*X*X*X ;
  case 8: return X*X*X*X*X*X*X*X ;        
  default:
     return X * Power(X,pow-1) ;
  }
}

struct ChimesJITev {
""", file = fheader)


print('#include "chimesJITev.h"', file=feval)
idx = -1

print_2b_header(feval, fheader)

pairidx = -1
tripidx = -1
quadidx = -1

## Scan through lines of params file.
for i in range(len(lines)):
    if pairsearch in lines[i]:
        idx = i
        natoms = 2
        pairidx += 1
    elif tripsearch in lines[i]:
        idx = i
        natoms = 3
        tripidx += 1
    elif quadsearch in lines[i]:
        idx = i
        natoms = 4
        quadidx += 1
    elif chebysearch in lines[i]:
        f = lines[i].split()
        nparams = int(f[2])
        continue
    else:
        continue

    if ( natoms == 2 ) :
        f = lines[idx].split()
    else:
        f = lines[idx+1].split()

    atoms = f[-natoms:]        

    if "TOTAL" in lines[idx+2] and natoms > 2:
        f = lines[idx+2].split()
        nparams = int(f[-1])

    npairs = int(natoms * (natoms - 1) / 2)

    print("cluster = \\", file=fmath)

    if ( natoms == 2 ):
        param_offset = 2
    else:
        param_offset = 5
    
    for j in range(nparams):
        f = lines[idx+param_offset+j].split()
        pow = [0] * npairs

        if ( natoms == 2 ) :
            pow[0] = int(f[0]) + 1
        else:
            for k in range(npairs):
                pow[k] = int(f[1+k])
            
        fcoeff = float(f[-1])
        coeff = f[-1]
    
        if ( True ) :   #### abs(fcoeff) > 0.0 ) :
            if ( j != 0 ):
                print(" + ", end="", file=fmath)
            else:
                print("   ", end="", file=fmath)

            coeff = coeff.replace("e+","*^+")
            coeff = coeff.replace("e-","*^-")        
            print(coeff + " ", end="", file=fmath)
            for k in range(npairs) :
                print("ChebyshevT[%d,x%d] " % (pow[k], k), end="", file=fmath)

            if ( j != nparams - 1 ):        
                print("\\", file=fmath)
            else:
                print("", file=fmath)
    
    fname = "".join(atoms) + ".c"
    func_name = "".join(atoms) 
    print("clusterh = HornerForm[cluster]", file=fmath)
    print("ccluster = CForm[clusterh]", file=fmath)
    print("dx0 = D[clusterh,x0]", file=fmath)
    print("dh0 = CForm[HornerForm[dx0]]", file=fmath)

    if natoms > 2 :
        print("dx1 = D[clusterh,x1]", file=fmath)
        print("dh1 = CForm[HornerForm[dx1]]", file=fmath)
        print("dx2 = D[clusterh,x2]", file=fmath)
        print("dh2 = CForm[HornerForm[dx2]]", file=fmath)

    if natoms == 2:
        print("WriteLine[file, \" \"]", file=fmath)
        print(f"WriteLine[file,\"void ChimesJITev::{func_name}(double x0, double *e, double *f0)\"]", file=fmath)

        ## Definition in header
        print(f"   void {func_name}(double x0, double *e, double *f0) ;", file = fheader)        

        ## Entry in evaluator.
        print(f"   case {pairidx}:", file = feval)
        print(f"   ChimesJITev::{func_name}(x0, e, f0) ;", file = feval)        
        print( "   break ;", file = feval) ;
    elif natoms == 3:
        if tripidx == 0 :
            ## Start the 3 body evaluator
            print_3b_header(feval, fheader)
            
        ## Begin function definition
        print("WriteLine[file, \" \"]", file=fmath)
        print(f"WriteLine[file,\"void ChimesJITev::{func_name}(double x0, double x1, double x2, double *e, \
        double *f0, double *f1, double *f2)\"]", file=fmath)

        ## Definition in header
        print(f"   void {func_name}(double x0, double x1, double x2, double *e, double *f0, double *f1, double *f2) ;", file = fheader)        

        ## Entry in evaluator.
        print(f"   case {tripidx}:", file = feval)
        print(f"   ChimesJITev::{func_name}(x0, x1, x2, e, f0, f1, f2) ;", file = feval)        
        print( "   break ;", file = feval) ;
    elif natoms == 4:
        if quadidx == 0 :
            ## Start the 4 body evaluator
            print_4b_header(feval, fheader)
       

            
        print("dx3 = D[clusterh,x3]", file=fmath)
        print("dh3 = CForm[HornerForm[dx3]]", file=fmath)
        print("dx4 = D[clusterh,x4]", file=fmath)
        print("dh4 = CForm[HornerForm[dx4]]", file=fmath)
        print("dx5 = D[clusterh,x5]", file=fmath)
        print("dh5 = CForm[HornerForm[dx5]]", file=fmath)
        print("WriteLine[file, \" \"]", file=fmath)            
        print(f"WriteLine[file,\"void ChimesJITev::{func_name}(double x0, double x1, double x2, double x3, \
        double x4, double x5, double *e, \
        double *f0, double *f1, double *f2, \
        double *f3, double *f4, double *f5 ) \"]", file=fmath)
        print(f"   case {quadidx}:", file = feval)
        print(f"   ChimesJITev::{func_name}(x0, x1, x2, x3, x4, x5, e, f0, f1, f2, f3, f4, f5) ;", file = feval)        
        print( "   break ;", file = feval) ;

        ## Definition in header
        print(f"   void {func_name}(double x0, double x1, double x2, double x3, double x4, double x5, double *e, double *f0, double *f1, double *f2, double *f3, double *f4, double *f5) ;", file = fheader)

    # Evaluate energy and f0 for all cluster types.
    print("WriteString[file, \"{\\n *e = \\n\"]", file=fmath)
    print("WriteString[file, ccluster]", file=fmath)
    print("WriteString[file, \";\\n\"]", file=fmath)
    print("WriteString[file, \"\\n *f0 = \\n\"]", file=fmath)
    print("WriteString[file, dh0]", file=fmath)
    print("WriteString[file, \";\\n\"]", file=fmath)
    
    if ( natoms > 2 ):
        print("WriteString[file, \"\\n *f1 = \\n\"]", file=fmath)
        print("WriteString[file, dh1]", file=fmath)
        print("WriteString[file, \";\\n\"]", file=fmath)

        print("WriteString[file, \"\\n *f2 = \\n\"]", file=fmath)
        print("WriteString[file, dh2]", file=fmath)
        print("WriteString[file, \";\\n\"]", file=fmath)

    if natoms == 4:
        print("WriteString[file, \"\\n *f3 = \\n\"]", file=fmath)
        print("WriteString[file, dh3]", file=fmath)
        print("WriteString[file, \";\\n\"]", file=fmath)

        print("WriteString[file, \"\\n *f4 = \\n\"]", file=fmath)
        print("WriteString[file, dh4]", file=fmath)
        print("WriteString[file, \";\\n\"]", file=fmath)

        print("WriteString[file, \"\\n *f5 = \\n\"]", file=fmath)
        print("WriteString[file, dh5]", file=fmath)
        print("WriteString[file, \";\\n\"]", file=fmath)

    print("WriteString[file, \"}\\n\"]", file=fmath)

    if ( natoms == 2 ):
        print("ClearAll[ccluster, dh0, dx0]", file=fmath)
    elif ( natoms >= 3 ) :
        print("ClearAll[cluster, ccluster, dh0, dx0, dh1, dx1, dh2, dx2]", file=fmath)

    if ( natoms == 4 ) :
        print("ClearAll[dx3, dh3, dx4, dh4, dx5, dh5]", file=fmath)

if pairidx == -1 :
    print("Error: No pair interactions were found !")
    exit(1)
    
if tripidx == -1 :
    ## Start a blank 3 body evaluator
    print_3b_header(feval, fheader)

if quadidx == -1 :
    ## Start a blank 4 body evaluator
    print_4b_header(feval, fheader)

# Finish the 4 body evaluator
print("  default: printf(\"Bad quaduplet index in ChimesJIT\") ; exit(1) ; ", file = feval)            
print("  }", file = feval)
print("}", file = feval)

print("} ; ", file = fheader)


## Print the input for later use.
print( "static std::string jit_commands = \\", file = fheader)
for l in lines:
    l = l.rstrip()
    print("\"" + l + "\\n\"", file = fheader)
print(";", file = fheader)    

print("static std::string jit_file = \"" + file + "\";", file = fheader)
##current_datetime = datetime.now()
current_date = date.today() ;

print("static std::string jit_date = \"", file = fheader, end="")
print(current_date, file = fheader, end="")
print("\" ;", file = fheader)

feval.close()
fheader.close()
fmath.close()

exit_code = os.system(f"{mathematica} -script chimesjit.m") ;
if ( exit_code != 0 ):
    print("Error: Mathematica failed")
    exit(1)
else:
    print("Mathematica succeeded !")

os.rename("chimesJITev.h", f"chimesJITev.{model_name}.h")
os.rename("chimesJITev.cpp", f"chimesJITev.{model_name}.cpp")
os.rename("chimesJITcluster.cpp", f"chimesJITcluster.{model_name}.cpp")

